# ----------------------------------------------------------------------------
# GitHub Actions workflow to test building all code samples.
#
# See docs:
# - https://castle-engine.io/github_actions
# - https://docs.github.com/en/actions
# ----------------------------------------------------------------------------

name: Build All

on: [push, pull_request]

jobs:
  test-fpc:
    name: FPC stable
    runs-on: ubuntu-latest
    container: kambi/castle-engine-cloud-builds-tools:cge-none
    steps:
    - uses: actions/checkout@v4
    - run: make all

  test-fpc331:
    name: FPC 3.3.1
    runs-on: ubuntu-latest
    container: kambi/castle-engine-cloud-builds-tools:cge-none-fpc331
    steps:
    - uses: actions/checkout@v4
    - run: make all-fpc331

  delphi_test:
    name: Delphi
    strategy:
      matrix:
        host-label: [
          delphi_12
        ]
    runs-on: ${{ matrix.host-label }}
    steps:
      - uses: actions/checkout@v4
      - name: Delphi Build (Win32)
        run: make all-delphi-win32
      - name: Delphi Build (Win64)
        run: make all-delphi-win64
